services:
  api:
    volumes:
      - .:/usr/src/app

  chain:
    volumes:
      - .:/usr/src/app

  notifications:
    volumes:
      - .:/usr/src/app

  database:
    volumes:
      - ./pgdata:/var/lib/postgresql
