services:
  migration:
    build:
      context: .
      dockerfile: ./typeorm/Dockerfile
    env_file:
      - ./typeorm/.env
    depends_on:
      database:
        condition: service_healthy
    restart: "no"

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    env_file:
      - ./apps/api/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3001:3000"
    volumes:
      - ./cert:/usr/src/app/cert:ro
    depends_on:
      migration:
        condition: service_completed_successfully
      nats:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  chain:
    build:
      context: .
      dockerfile: ./apps/chain/Dockerfile
    env_file:
      - ./apps/chain/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      migration:
        condition: service_completed_successfully
      nats:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
    env_file:
      - ./apps/notifications/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3020:3020"
    depends_on:
      migration:
        condition: service_completed_successfully
      api:
        condition: service_started
      nats:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  nats:
    image: nats:2.10
    command:
      - "-js"
      - "-sd=/data/jetstream"
    ports:
      - "4222:4222"
    volumes:
      - nats:/data/jetstream
    restart: unless-stopped

  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    build: ./redis
    ports:
      - "6380:6379"
    volumes:
      - redis:/data
    restart: always

volumes:
  nats:
    driver: local
  postgres_data:
    driver: local
  redis:
    driver: local
